# Generated by Django 4.1 on 2023-10-11 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Oasisback", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="password_2",
            new_name="password2",
        ),
    ]
